title: <p align="center"> Manish Virmani </p>
logo: /assets/img/ML.png

description:
  <p align="center">
  
 
  <br>  
  Working in Pharma domain for 5 years.
  <br>
  </p>



theme: jekyll-theme-minimal
